corpus:
  corpus_file: corpus/corpus.h5
  root: corpus/dataset/maestro

model:
  _target_: model.hsa.HSA
  F: 324
  P: 32
  T: 128
  D: 128
  K: 6
  target_sr: 22050
  fft_bins: 2048
  hop_sample: 256
  bins_per_octave: 36
  weight_a: 0.5
  weight_b: 0.5
  weight_chroma: 0.2

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${train.batch_size}
  shuffle: ${train.shuffle}
  num_workers: ${train.num_workers}

train:
  epochs: 50
  batch_size: 7
  shuffle: True
  num_workers: 2
  warmup_steps: 4000

optimizer:
  _target_: torch.optim.Adam
  lr: 4e-4

scheduler:
  _target_: torch.optim.lr_scheduler.LambdaLR

torch:
  seed: 42
  cudnn_benchmark: True
  cudnn_deterministic: False
  allow_tf_32: True